version: '3.3'
services:

# Servicios principales

  badgrserver:
    image: 'ankrisrag/servidor-badgr:latest'
    volumes:
      - 'badgrserver_volume:/badgr_server'
      - ./backup_files/uwsgi.ini:/badgr_server/uwsgi.ini
      - ./backup_files/wsgi.py:/badgr_server/wsgi.py
      - ./backup_files/settings_local.py:/badgr_server/apps/mainsite/settings_local.py
    depends_on:
      - "db"
      - "memcached"
    command: uwsgi --ini uwsgi.ini
    links:
      - 'badgrui:badgr.ui'

  badgrui:
    image: 'ankrisrag/interfaz-badgr:latest'
    ports:
      - "4200:4200"

  moodle:
    image: 'bitnami/moodle:3'
    environment:
      - "MOODLE_DATABASE_HOST=mariadb"
      - "MOODLE_DATABASE_PORT_NUMBER=3306"
      - "MOODLE_DATABASE_USER=bn_moodle"
      - "MOODLE_DATABASE_NAME=bitnami_moodle"
      - "ALLOW_EMPTY_PASSWORD=yes"
      - "BITNAMI_DEBUG=true"
    volumes:
      - 'moodle_volume:/bitnami'
    depends_on:
      - "mariadb"
      - "proxy"
    links:
      - 'proxy:api.badgr.io'
      - 'proxy:badgr.io'
    ports:
      - "8081:8080"
      - "8444:8443"


# Servicios secundarios

  nginx:
    image: 'ankrisrag/nginx-badgr:latest'
    volumes:
      - 'badgrserver_volume:/badgr_server'
      - ./backup_files/nginx.conf:/etc/nginx/nginx.conf
      - ./backup_files/site.conf:/etc/nginx/sites-available/site.conf
    depends_on:
      - "badgrserver"
    ports:
      - "8080:80"
      - "4443:443"

  proxy:
    image: 'ankrisrag/proxy-badgr:latest'
    depends_on: 
      - "nginx"
    ports:
      - "8200:80"

  memcached:
    image: 'bitnami/memcached:latest'
    ports:
      - "11211:11211"
    expose:
      - "11211"

# Bases de datos

  db:
    image: 'mysql:5.6.39'
    environment:
      - "MYSQL_PASSWORD=password"
      - "MYSQL_HOST=db"
      - "MYSQL_ROOT_PASSWORD=password"
    volumes:
      - 'mysql_volume:/var/lib/mysql:rw'
      - ./backup_files/init.sql:/docker-entrypoint-initdb.d/init.sql
    expose:
      - "3306"
      
  mariadb:
    image: 'bitnami/mariadb:10.6'
    environment:
      - "MARIADB_USER=bn_moodle"
      - "MARIADB_DATABASE=bitnami_moodle"
      - "MARIADB_CHARACTER_SET=utf8mb4"
      - "MARIADB_COLLATE=utf8mb4_unicode_ci"
      - "ALLOW_EMPTY_PASSWORD=yes"
    volumes:
      - 'mariadb_volume:/bitnami'

volumes:

  badgrserver_volume: {}
  moodle_volume: {}
  mysql_volume: {}
  mariadb_volume: {}
